# Generated by Django 5.1.6 on 2025-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='actividades', verbose_name='Foto Adjunta'),
        ),
    ]
