# Generated by Django 5.1.6 on 2025-02-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planificacion', '0002_actividad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='email',
            field=models.EmailField(blank=True, default='correo@ejemplo.com', max_length=254, null=True, unique=True),
        ),
    ]
