# Generated by Django 5.1.6 on 2025-02-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planificacion', '0003_actividad_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
