# Generated by Django 5.1.6 on 2025-02-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planificacion', '0004_alter_actividad_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='email',
        ),
    ]
